# Generated by Django 4.1.1 on 2023-10-21 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0002_characterincomic_characterinseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='characterincomic',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarvelUniverse.character'),
        ),
        migrations.AddField(
            model_name='characterincomic',
            name='comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarvelUniverse.comic'),
        ),
        migrations.AddField(
            model_name='characterinseries',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarvelUniverse.character'),
        ),
        migrations.AddField(
            model_name='characterinseries',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarvelUniverse.series'),
        ),
        migrations.AddField(
            model_name='comic',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
