# Generated by Django 4.2.5 on 2023-11-10 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MarvelUniverse', '0005_rename_seriesreview_seriescomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriescomment',
            name='name',
        ),
        migrations.AddField(
            model_name='seriescomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
