# Generated by Django 4.2.5 on 2023-11-12 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MarvelUniverse', '0007_seriesreview_delete_seriescomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('user_comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MarvelUniverse.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='SeriesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MarvelUniverse.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.DeleteModel(
            name='SeriesReview',
        ),
    ]
