# Generated by Django 4.1.1 on 2023-11-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0009_favoriteseries_favoritecomic_favoritecharacter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SeriesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SeriesChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200, null=True)),
                ('character_image', models.URLField(null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarvelUniverse.seriesquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ComicChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200, null=True)),
                ('character_image', models.URLField(null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarvelUniverse.comicquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=200, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarvelUniverse.characterquestion')),
            ],
        ),
    ]
