# Generated by Django 4.1.1 on 2023-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0009_favoriteseries_favoritecomic_favoritecharacter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(),
        ),
    ]