# Generated by Django 4.2.7 on 2023-11-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0010_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='rank_img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
