# Generated by Django 4.1.1 on 2023-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0011_characterquestion_comicquestion_seriesquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterquestion',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comicquestion',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seriesquestion',
            name='description',
            field=models.TextField(),
        ),
    ]
