# Generated by Django 4.2.7 on 2023-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0011_userdata_rank_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='rank_img_url',
        ),
        migrations.AddField(
            model_name='userdata',
            name='trophy_img',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
