# Generated by Django 4.1.1 on 2023-11-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0010_characterquestion_comicquestion_seriesquestion_and_more'),
        ('MarvelUniverse', '0011_userdata_rank_img_url'),
    ]

    operations = [
    ]
