# Generated by Django 4.2.7 on 2023-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0012_merge_20231123_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='rank_img_url',
        ),
        migrations.AddField(
            model_name='userdata',
            name='trophy_img',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_img_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
