# Generated by Django 4.1.1 on 2023-11-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0012_merge_20231123_1420'),
        ('MarvelUniverse', '0013_remove_userdata_rank_img_url_userdata_trophy_img_and_more'),
    ]

    operations = [
    ]
