# Generated by Django 4.1.1 on 2023-11-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0014_merge_20231124_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='trophy_img',
        ),
        migrations.AddField(
            model_name='userdata',
            name='medal_img',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_img_url',
            field=models.URLField(blank=True, default='https://i.ibb.co/t8GgdVp/default-profile.png', max_length=500, null=True),
        ),
    ]
