# Generated by Django 4.2.7 on 2023-11-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelUniverse', '0010_alter_character_description_alter_comic_description_and_more'),
        ('MarvelUniverse', '0015_remove_userdata_trophy_img_userdata_medal_img_and_more'),
    ]

    operations = [
    ]
